version: 2.1

jobs:
  test:
    docker: 
      - image: alpine:latest
    steps:
      - run: return 1
      - run: 
          command: echo failure
          when: on_fail

workflows:
  # Name the workflow "welcome"
  pipeline-test:
    jobs:
      - test