# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo This is the Workflow ID $(CIRCLE_WORLFLOW_ID)

jobs:
  test:
    docker: 
      - image: alpine:latest
    steps:
      - print_pipeline_id 

workflows:
  # Name the workflow "welcome"
  pipeline-test:
    jobs:
      - test
